Return-Path: <linux-spi-owner@vger.kernel.org>
X-Original-To: lists+linux-spi@lfdr.de
Delivered-To: lists+linux-spi@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id F260B599D90
	for <lists+linux-spi@lfdr.de>; Fri, 19 Aug 2022 16:28:35 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1349157AbiHSO02 (ORCPT <rfc822;lists+linux-spi@lfdr.de>);
        Fri, 19 Aug 2022 10:26:28 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:60638 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1349361AbiHSO0V (ORCPT
        <rfc822;linux-spi@vger.kernel.org>); Fri, 19 Aug 2022 10:26:21 -0400
Received: from ams.source.kernel.org (ams.source.kernel.org [IPv6:2604:1380:4601:e00::1])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 76C21EA311;
        Fri, 19 Aug 2022 07:26:08 -0700 (PDT)
Received: from smtp.kernel.org (relay.kernel.org [52.25.139.140])
        (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
        (No client certificate requested)
        by ams.source.kernel.org (Postfix) with ESMTPS id 021F5B827E5;
        Fri, 19 Aug 2022 14:26:07 +0000 (UTC)
Received: by smtp.kernel.org (Postfix) with ESMTPSA id E1F4BC433C1;
        Fri, 19 Aug 2022 14:26:04 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/simple; d=kernel.org;
        s=k20201202; t=1660919165;
        bh=+6oUBYP5Akr39UzKlRCjPl3FcOmUxW9kETDioIzedJA=;
        h=From:To:Cc:In-Reply-To:References:Subject:Date:From;
        b=Io75iAELdIefKSpR712qfpmWJtvGFvUwTSLO4oZ7vN0DolpA6M9MZoFOTq/19Wefv
         JeE1LmYo5440fcRt6nnaLghwlzES1lld7coqUmNGrP8Igh0rc5nOu7QENMWon8gDA0
         8gUMH3h8TEehCMLCcpDBuZ2ROVOYeORdnjLrYZ8PsAGpIYXBGJ33RvHRJxn9V2niAb
         xIuliBfk+KGkbrV0rck4NT1fkDOrk9O46WzokqU0uhJMOdFdjhqMjnJTXuEkMC8BkT
         WpgA9wrh12pd8FY28tFvFEarYbt4JjApAWN15CnUkLqhiAQfmpdDfXHbuC7yFSG7s3
         ZDS6gOgRfh9gw==
From:   Mark Brown <broonie@kernel.org>
To:     linux-kernel@vger.kernel.org,
        Wolfram Sang <wsa+renesas@sang-engineering.com>
Cc:     linux-spi@vger.kernel.org
In-Reply-To: <20220818210107.7373-1-wsa+renesas@sang-engineering.com>
References: <20220818210107.7373-1-wsa+renesas@sang-engineering.com>
Subject: Re: [PATCH] spi: move from strlcpy with unused retval to strscpy
Message-Id: <166091916465.94432.6649632671608591710.b4-ty@kernel.org>
Date:   Fri, 19 Aug 2022 15:26:04 +0100
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
X-Mailer: b4 0.10.0-dev-fe10a
X-Spam-Status: No, score=-7.1 required=5.0 tests=BAYES_00,DKIMWL_WL_HIGH,
        DKIM_SIGNED,DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_HI,
        SPF_HELO_NONE,SPF_PASS,T_SCC_BODY_TEXT_LINE autolearn=ham
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-spi.vger.kernel.org>
X-Mailing-List: linux-spi@vger.kernel.org

On Thu, 18 Aug 2022 23:01:07 +0200, Wolfram Sang wrote:
> Follow the advice of the below link and prefer 'strscpy' in this
> subsystem. Conversion is 1:1 because the return value is not used.
> Generated by a coccinelle script.
> 
> 

Applied to

   https://git.kernel.org/pub/scm/linux/kernel/git/broonie/spi.git for-next

Thanks!

[1/1] spi: move from strlcpy with unused retval to strscpy
      commit: 51e99de583697cc073ef8888690675b07fe8ef3c

All being well this means that it will be integrated into the linux-next
tree (usually sometime in the next 24 hours) and sent to Linus during
the next merge window (or sooner if it is a bug fix), however if
problems are discovered then the patch may be dropped or reverted.

You may get further e-mails resulting from automated or manual testing
and review of the tree, please engage with people reporting problems and
send followup patches addressing any issues that are reported if needed.

If any updates are required or you are submitting further changes they
should be sent as incremental updates against current git, existing
patches will not be replaced.

Please add any relevant lists and maintainers to the CCs when replying
to this mail.

Thanks,
Mark
